services:
  # 1) Editor shell from apps/editor
  - type: web
    name: opentrain-editor
    runtime: node
    rootDir: apps/editor
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DOCSVC_URL
        value: https://opentrain-docsvc.onrender.com
      - key: DOCSVC_API_KEY
        sync: false
      - key: EMBED_ISSUER_SECRET
        sync: false
      - key: EMBED_JWT_SECRET
        sync: false
    buildFilter:
      paths:
        - apps/editor/**

  # 2) Node doc service from apps/docsvc
  - type: web
    name: opentrain-docsvc
    runtime: node
    rootDir: apps/docsvc
    plan: starter
    autoDeploy: true
    buildCommand: "npm ci"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DOCSVC_API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://*.bubbleapps.io,https://opentrain-editor.onrender.com
    buildFilter:
      paths:
        - apps/docsvc/**
