databases:
  - name: opentrain-docs
    plan: free

services:
  # 1) Static editor from apps/editor
  - type: web
    name: opentrain-editor
    runtime: static
    rootDir: apps/editor
    buildCommand: ""
    staticPublishPath: public
    autoDeploy: true
    headers:
      - path: /*
        name: Content-Security-Policy
        value: frame-ancestors https://*.bubbleapps.io https://*.opentrain.ai;
      - path: /index.html
        name: Cache-Control
        value: no-store
    buildFilter:
      paths:
        - apps/editor/**

  # 2) Node doc service from apps/docsvc
  - type: web
    name: opentrain-docsvc
    runtime: node
    rootDir: apps/docsvc
    plan: starter
    autoDeploy: true
    buildCommand: "npm ci"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: opentrain-docs
          property: connectionString
      - key: DOCSVC_API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://*.bubbleapps.io,https://opentrain-editor.onrender.com
    buildFilter:
      paths:
        - apps/docsvc/**
